nelmio_cors:
    defaults:
        allow_origin: ['http://127.0.0.1:8000', 'http://localhost:8000']
        allow_credentials: true
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: ['Link']
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
        max_age: 3600
    paths:
        '^/api/':
            allow_origin: ['http://127.0.0.1:8000', 'http://localhost:8000']
